services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: preInscriptionForm
    restart: unless-stopped
    ports:
      - "8030:8030"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge