server {
    listen 8030;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

   location /API/ {
    proxy_pass https://strobe-negation-moisture.ngrok-free.dev;
    proxy_set_header Host grunt-cascade-protozoan.ngrok-free.dev;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header ngrok-skip-browser-warning "true";
}

    location / {
        try_files $uri /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}