/**
 * Liste des pays (nomenclature ISO en français) utilisée pour le champ
 * "Pays d'origine". Ce champ est indépendant de la nationalité choisie —
 * une personne peut avoir une nationalité différente de son pays d'origine.
 */
export const COUNTRY_OPTIONS: string[] = [
  'Afghanistan',
  'Afrique du Sud',
  'Aland (Iles)',
  'Albanie',
  'Algérie',
  'Allemagne',
  'Andorre',
  'Angola',
  'Anguilla',
  'Antarctique',
  'Antigua-et-Barbuda',
  'Arabie Saoudite',
  'Argentine',
  'Arménie',
  'Aruba',
  'Australie',
  'Autriche',
  'Azerbaïdjan',
  'Bahamas',
  'Bahreïn',
  'Bangladesh',
  'Barbade',
  'Bélarus',
  'Belgique',
  'Belize',
  'Bénin',
  'Bermudes',
  'Bhoutan',
  'Bolivie (Etat plurinational de)',
  'Bonaire, Saint-Eustache et Saba',
  'Bosnie-Herzégovine',
  'Botswana',
  'Bouvet (Ile)',
  'Brésil',
  'Brunéi Darussalam',
  'Bulgarie',
  'Burkina Faso',
  'Burundi',
  'Caïmans (Iles)',
  'Cambodge',
  'Cameroun',
  'Canada',
  'Cabo Verde',
  'République centrafricaine',
  'Chili',
  'Chine',
  'Chypre',
  'Cocos (Iles) / Keeling  (Iles)',
  'Colombie',
  'Comores',
  'Congo',
  'Congo (République démocratique du)',
  'Corée (République populaire démocratique de)',
  'Corée (République de)',
  'Costa Rica',
  "Côte d'Ivoire",
  'Croatie',
  'Cuba',
  'Curaçao',
  'Danemark',
  'Djibouti',
  'Dominicaine (République)',
  'Dominique',
  'Egypte',
  'El Salvador',
  'Emirats arabes unis',
  'Equateur',
  'Erythrée',
  'Espagne',
  'Estonie',
  'Micronésie (Etats fédérés de)',
  "Etats-Unis d'Amérique",
  'Ethiopie',
  'Falkland (Iles) / Malouines (Iles)',
  'Féroé (Iles)',
  'Fidji',
  'Finlande',
  'France',
  'Gabon',
  'Gambie',
  'Géorgie',
  'Géorgie du Sud-et-les Iles Sandwich du Sud',
  'Ghana',
  'Gibraltar',
  'Grèce',
  'Grenade',
  'Groenland',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernesey',
  'Guinée',
  'Guinée équatoriale',
  'Guinée-Bissau',
  'Guyana',
  'Guyane française',
  'Haïti',
  'Heard-et-Iles MacDonald (Ile)',
  'Honduras',
  'Hong Kong',
  'Hongrie',
  'Christmas (Ile)',
  'Ile de Man',
  'Norfolk (Ile)',
  'Cook (Iles)',
  'Mariannes du Nord (Iles)',
  "Iles mineures éloignées des Etats-Unis",
  'Turks et Caïcos (Iles)',
  'Vierges britanniques (Iles)',
  'Vierges des Etats-Unis (Iles)',
  'Inde',
  'Indonésie',
  "Iran (République Islamique d')",
  'Iraq',
  'Irlande',
  'Islande',
  'Israël',
  'Italie',
  'Jamaïque',
  'Japon',
  'Jersey',
  'Jordanie',
  'Kazakhstan',
  'Kenya',
  'Kirghizistan',
  'Kiribati',
  'Koweït',
  'Lao (République démocratique populaire)',
  'Lesotho',
  'Lettonie',
  'Liban',
  'Libéria',
  'Libye',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Macao',
  'Macédoine (ex-République yougoslave de)',
  'Madagascar',
  'Malaisie',
  'Malawi',
  'Maldives',
  'Mali',
  'Malte',
  'Maroc',
  'Marshall (Iles)',
  'Martinique',
  'Maurice',
  'Mauritanie',
  'Mayotte',
  'Mexique',
  'Moldova (République de)',
  'Mongolie',
  'Monténégro',
  'Montserrat',
  'Mozambique',
  'Myanmar',
  'Namibie',
  'Nauru',
  'Népal',
  'Nicaragua',
  'Niger',
  'Nigéria',
  'Niue',
  'Norvège',
  'Nouvelle-Calédonie',
  'Nouvelle-Zélande',
  'Oman',
  'Ouganda',
  'Ouzbékistan',
  'Pakistan',
  'Palaos',
  "Palestine (Etat de)",
  'Panama',
  'Papouasie-Nouvelle-Guinée',
  'Paraguay',
  'Pays-Bas',
  'Pérou',
  'Philippines',
  'Pitcairn',
  'Pologne',
  'Polynésie française',
  'Porto Rico',
  'Portugal',
  'Monaco',
  'Qatar',
  'Réunion',
  'Roumanie',
  "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord",
  'Russie (Fédération de)',
  'Rwanda',
  'Sahara occidental',
  'Saint-Barthélemy',
  'Sainte-Hélène, Ascension et Tristan Da Cunha',
  'Sainte-Lucie',
  'Saint-Kitts-Et-Nevis',
  'Saint-Martin (partie néerlandaise)',
  'Saint-Marin',
  'Saint-Martin (partie française)',
  'Saint-Pierre-et-Miquelon',
  'Saint-Siège',
  'Saint-Vincent-et-les Grenadines',
  'Salomon (Iles)',
  'Samoa',
  'Samoa américaines',
  'Sao Tomé-et-Principe',
  'Sénégal',
  'Serbie',
  'Seychelles',
  'Sierra Leone',
  'Singapour',
  'Slovaquie',
  'Slovénie',
  'Somalie',
  'Soudan',
  'Soudan du Sud',
  'Sri Lanka',
  'Suède',
  'Suisse',
  'Suriname',
  "Svalbard et l'Ile Jan Mayen",
  'Swaziland',
  'République arabe syrienne',
  'Tadjikistan',
  'Taïwan (Province de Chine)',
  'Tanzanie (République-Unie de)',
  'Tchad',
  'Tchèque (République)',
  'Terres australes françaises',
  "Indien (Territoire britannique de l'océan)",
  'Thaïlande',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinité-et-Tobago',
  'Tunisie',
  'Turkménistan',
  'Turquie',
  'Tuvalu',
  'Ukraine',
  'Uruguay',
  'Vanuatu',
  'Venezuela (République bolivarienne du)',
  'Viet Nam',
  'Wallis-et-Futuna',
  'Yémen',
  'Zambie',
  'Zimbabwe',
];
