import type { PreRegistrationFormValues } from '@/types';
import { NO_ACTIVITY_SECTOR_ID } from './options';

export const DEFAULT_FORM_VALUES: PreRegistrationFormValues = {
  MatriculeBac: '',
  Nom: '',
  Prenom: '',
  Sexe: 'M',
  DateNais: '',
  LieuNais: '',
  PaysOrigine: 'Congo',
  Photo: '',
  Téléphone1: '',
  Téléphone2: '',
  Email: '',
  Adresse: '',
  NomPrenom: '',
  IDNationalité: 0,
  DésignNationalité: '',
  Boursier: false,
  IDArrondissement: 0,
  Quartier: '',
  SituationMatrimoniale: 1,
  SecteurActivité: NO_ACTIVITY_SECTOR_ID,
  ExpérienceProf: 0,
  CréateurEntreprise: false,
  ProfessionExercée: '',
  FonctionActuelle: '',
  StructureTravail: '',
  CatégoriePro: 0,
  OrphelinPère: false,
  OrphelinMère: false,
  FilleMère: false,
  Autochtone: false,
  Handicapé: false,
  NomPrenomPère: '',
  FonctionPère: '',
  LieuTravailPère: '',
  AdressePère: '',
  TéléphonePère: '',
  NomPrenomMère: '',
  FonctionMère: '',
  LieuTravailMère: '',
  AdresseMère: '',
  TéléphoneMère: '',
  NomPrénomTuteur: '',
  FonctionTuteur: '',
  LieuTravailTuteur: '',
  AdresseTuteur: '',
  TéléphoneTuteur: '',
  RelationAvecTuteur: '',
  AnneeAcademique: '',
  Niveau: 0,
  IDParcours: 0,
  // A single pre-populated row: DiplomasStep now edits a fixed `diplomas.0.*`
  // path (no dynamic add/remove), so `_localId` must already be valid from
  // the start — it's never exposed as an input.
  diplomas: [
    {
      _localId: 'diploma-0',
      Diplôme: '',
      Mention: '',
      Année: new Date().getFullYear(),
      ETS: '',
      Lieu: '',
      NiveauDiplome: 0,
    },
  ],
};
