/**
 * Liste des quartiers de Brazzaville
 */
export const NEIGHBORHOODS = [
  'Centre sportif',
  'Mayoma',
  'Météo',
  'Moukoudzi-Ngouaka',
  'Ngangouoni',
  'Diata',
  'Kingouari',
  'Kinsoundi',
  'Niania',
  'Sita Dia Tsiolo',
  'Mamba',
  'Ngoma',
  'Nimbi',
  'Dahomey',
  'Mbama',
  'Mpissa',
  'Nkeoua',
  'Total',
  'Tahiti',
  'La Glacière',
  'Saint-Pierre',
  'Saint-Pierre-Claver',
  'Marché Poto-Poto',
  'Unité Africaine',
  'Église Kimbanguiste',
  'CHU',
  'Hyper-centre',
  'Gare centrale',
  'Anciens Combattants',
  'Plateau des 15 ans',
  'Dix Maisons',
  'CEG de la Paix',
  'Marché 10 Francs',
  'CEG Matsoua',
  'Moukondo',
  'La Poudrière',
  'Massamba-Raphaël',
  'Maison Commune de Ouenzé',
  'Jane Vial',
  'Mouleke',
  'Moukondo-Ouenzé',
  'Bouemba',
  'Sainte-Marie de Ouenzé',
  'Manzanza',
  'Mpila Cent Fils',
  'Mikalou',
  'Lycée',
  'Kimbangu-Mikalou',
  'Mpila',
  'Intendance',
  'Texaco-Tsiémé',
  'Fleuve Congo',
  'Joseph Ngobali',
  'Champ de Tir',
  'Gaston Lenda',
  'Simba-Pelle',
  'Volonté populaire',
  'Maman Mboualé',
  'Ngamakosso',
  'Massengo',
  'Soprogi',
  'Ebina',
  'Manianga',
  'Nzoko-Mbimi',
  'Massina',
  'Mpiéré-Miré',
  'Kibouendé',
  'Indzouli',
  'Kahounga',
  'Moutabala',
  'Mbouala',
  'Ngambio',
  'Diboulou',
  'Mitoko',
  'Poto-Poto du Djoué',
  'Madibou',
  'Kibina',
  'Moussosso',
  'Ntsangamani',
  'Kombé',
  'Mbouono',
  'Massissia',
  'Mafouta',
  'Mayanga',
  'Mansimou',
  'Itsali',
  'Mikalou-Madzouna',
  'Matari',
  'Nkombo',
  'Jacques Opangault',
  'Impoh-Manianga',
  'Makabandilou',
] as const;

export type Neighborhood = typeof NEIGHBORHOODS[number];
